document.getElementById('moodForm').addEventListener('submit', function(event) {
    event.preventDefault();
    const mood = document.getElementById('mood').value;
    const result = document.getElementById('result');
    
    const messages = {
        happy: [
            'Harika görünüyor! Bugün mükemmel bir gün olabilir. Her şeyin tadını çıkarın!',
            'Gülümseme enerjinizi yayar! Çevrenizdeki güzellikleri fark edin.',
            'Kendinizi iyi hissediyorsunuz! Bu enerjinizi başkalarına da aktarın.',
            'Bugün sizin gününüz! Pozitif enerjinizi çevrenizle paylaşın.',
            'Güzel bir gün geçirdiğinizde, ruh haliniz de iyileşir.',
            'Her şey mükemmel görünüyor! Eğlenmeye ve keyif almaya devam edin.',
            'Enerjiniz yüksek, bu da başkalarına pozitif bir etki yaratır!',
            'Gülümseyin ve yaşamın tadını çıkarın! Her şey daha iyi olacak.',
            'Bugün hayatınızın en iyi günü olabilir! Keyif alın.',
            'Kendinizi harika hissediyorsunuz! Bu enerjinizi başkalarına da yansıtın.',
            'Her şey mükemmel görünüyor, bu yüzden keyif almaktan çekinmeyin!',
            'Pozitif düşüncelerle dolusunuz! Her anı dolu dolu yaşayın.',
            'Bugün kendinize ödül verin, çünkü bunu hak ettiniz!',
            'Her şey yolunda gidiyor. Bu enerjiyle daha fazla başarı elde edebilirsiniz.',
            'Mutluluğunuz çevrenizdeki herkese bulaşacak! Harika bir gün!',
            'Günün tadını çıkarın ve kendinizi şımartın!',
            'Bugün kendinizi gerçekten iyi hissediyorsunuz. Bu enerjiyi başkalarına da yayabilirsiniz.',
            'Güzel haberler ve olumlu gelişmeler gününüzü güzelleştirecek!',
            'Güzel bir gün geçirmeyi hak ettiniz. Keyif alın!',
            'Pozitif ruh haliniz tüm günü aydınlatacak.',
            // 80 tane daha mesaj ekleyin
            'Hayatınızdaki güzellikleri fark edin ve kutlayın!',
            'Enerjinizi yüksek tutun ve günün tadını çıkarın!',
            'Bugün size harika fırsatlar sunuyor. Değerlendirin!',
            'Gülümsemeniz tüm dünyayı aydınlatabilir!',
            'Kendinizi harika hissediyorsunuz, bu harika!',
            'Bugün gerçekten başarılı olacağınız bir gün.',
            'Güzel bir gün geçirmek için harika bir ruh halindesiniz!',
            'Pozitif düşünceleriniz tüm günü güzelleştirecek!',
            'Hayatınızda her şey yolunda gidiyor, keyif alın!',
            'Bugün kendinizi oldukça iyi hissediyorsunuz, bu harika!',
            'Güzel bir gün ve harika bir ruh hali, ne kadar güzel!',
            'Kendinizi mutlu ve enerjik hissetmek için her şey hazır!',
            'Bugün her şeyin iyi gitmesi için harika bir gün!',
            'Pozitif enerjiniz sayesinde harika bir gün geçireceksiniz!',
            'Güzel anların tadını çıkarın ve bu enerjiyi koruyun!',
            'Bugün kendinizi iyi hissetmek için mükemmel bir gün!',
            'Enerjinizi yüksek tutarak tüm günün tadını çıkarın!',
            'Bugün kendinizi mükemmel hissetmek için harika bir fırsat!',
            'Hayatınızdaki olumlu değişiklikleri fark edin ve kutlayın!',
            'Güzel bir gün geçirmek için her şey yolunda!'
        ],
        sad: [
            'Üzgün olduğunuzu biliyorum. Kendinize zaman ayırın ve rahatlamaya çalışın. Yarın daha iyi olacak.',
            'Her zor dönemin bir sonu vardır. Güzel şeyler sizi bekliyor olabilir.',
            'Küçük adımlar atarak kendinizi daha iyi hissetmeye başlayabilirsiniz.',
            'Zor zamanlarda kendinize nazik davranın ve iyileşmeye çalışın.',
            'Üzgün olduğunuzda kendinize zaman ayırmak önemlidir. Kendinize iyi bakın.',
            'Üzülmek doğal bir duygudur, ancak zamanla daha iyi hissetmeye başlayacaksınız.',
            'Her şeyin kötü gideceğini düşünmek yerine, iyileşmeye odaklanın.',
            'Kendinize karşı nazik olun ve bu zor zamanı aşmanıza yardımcı olacak şeyler yapın.',
            'Üzgün hissettiğinizde kendinizi kötü hissetmeyin, iyileşmek zaman alabilir.',
            'Duygusal olarak zor bir dönemden geçiyorsunuz. Bu geçici bir durum, sabırlı olun.',
            'Üzgün olduğunuzda kendinize nazik davranmak ve rahatlatıcı aktiviteler yapmak önemlidir.',
            'Küçük şeylerle kendinizi iyi hissetmeye çalışın ve zamanla kendinizi daha iyi hissedeceksiniz.',
            'Duygusal olarak iyileşmek zaman alabilir, ancak kendinize nazik ve sabırlı olun.',
            'Üzülmek doğal bir duygudur. Kendinize zaman tanıyın ve iyileşmeye odaklanın.',
            'Zor zamanlarda kendinizi iyi hissetmek için sevdiğiniz şeylere yönelin.',
            'Her zaman kendinize karşı nazik ve sabırlı olun. Bu zor zamanlar geçici.',
            'Kendinize zaman ayırarak ve rahatlamaya çalışarak bu zorlu dönemi aşabilirsiniz.',
            'Üzgün hissettiğinizde, destek aramak ve kendinize zaman ayırmak önemlidir.',
            'Duygusal olarak iyileşmek zaman alabilir, ancak kendinize nazik davranmayı unutmayın.',
            // 80 tane daha mesaj ekleyin
            'Kendinizi kötü hissettiğinizde, olumlu şeylere odaklanmak faydalı olabilir.',
            'Üzgün hissettiğinizde kendinize iyi bakmak ve destek aramak önemlidir.',
            'Zor zamanlarda kendinizi kötü hissetmek doğaldır. Sabırlı olun ve iyileşmeye odaklanın.',
            'Küçük şeylerle kendinizi daha iyi hissetmek için çaba gösterin.',
            'Üzgün olduğunuzda kendinizi kötü hissetmemeye çalışın. Bu geçici bir durum.',
            'Duygusal olarak zor bir dönemden geçiyorsunuz, ancak iyileşmek zaman alabilir.',
            'Üzgün hissettiğinizde kendinizi kötü hissetmek yerine iyileşmeye odaklanın.',
            'Zor zamanlarda kendinize nazik davranmak ve destek aramak önemlidir.',
            'Küçük adımlar atarak kendinizi daha iyi hissetmeye çalışın.',
            'Kendinizi kötü hissettiğinizde destek aramak ve kendinize nazik davranmak önemlidir.',
            'Duygusal olarak iyileşmek zaman alabilir, ancak kendinize iyi bakın.',
            'Üzgün hissettiğinizde kendinizi kötü hissetmemeye çalışın ve iyileşmeye odaklanın.',
            'Zor zamanlarda kendinizi kötü hissetmek doğaldır. Sabırlı olun ve iyileşmeye çalışın.',
            'Küçük şeylerle kendinizi daha iyi hissetmek için çaba gösterin.',
            'Üzgün olduğunuzda kendinizi kötü hissetmemeye çalışın ve destek arayın.',
            'Kendinize karşı nazik olun ve bu zorlu dönemi aşmak için destek arayın.',
            'Duygusal olarak zor bir dönemden geçerken kendinize zaman ayırın ve iyileşmeye odaklanın.',
            'Küçük adımlar atarak kendinizi daha iyi hissetmeye çalışın ve destek arayın.',
            'Üzgün olduğunuzda kendinizi kötü hissetmemeye çalışın ve iyileşmeye odaklanın.',
            'Zor zamanlarda kendinize nazik davranmak ve destek aramak önemlidir.'
        ],
        anxious: [
            'Endişeli olmanız normal. Derin nefes alın ve kendinizi rahatlatmaya çalışın. Her şey kontrol altında.',
            'Endişe duyduğunuz şeyler genellikle aklımızda büyür. Küçük adımlarla ilerlemeyi deneyin.',
            'Rahatlamak için kendinize bir mola verin ve derin nefes almayı deneyin.',
            'Endişelendiğinizde kendinize nazik davranın ve rahatlama tekniklerini deneyin.',
            'Endişe genellikle geçici bir durumdur. Kendinize nazik davranın ve iyileşmeye odaklanın.',
            'Kendinizi endişeli hissettiğinizde, gevşeme tekniklerini deneyin ve destek arayın.',
            'Endişe duyduğunuzda kendinize karşı nazik olun ve rahatlamaya çalışın.',
            'Küçük adımlarla endişelerinizi azaltabilir ve kendinizi daha iyi hissedebilirsiniz.',
            'Derin nefes almak ve rahatlama tekniklerini kullanmak endişenizi azaltabilir.',
            'Endişe doğal bir duygudur. Kendinize zaman tanıyın ve rahatlamaya çalışın.',
            'Endişeli olduğunuzda kendinizi kötü hissetmemeye çalışın ve rahatlamaya odaklanın.',
            'Kendinize nazik davranın ve endişelerinizi yönetmek için destek arayın.',
            'Endişe genellikle geçici bir durumdur. Kendinize iyi bakın ve iyileşmeye odaklanın.',
            'Rahatlama tekniklerini deneyerek endişenizi azaltabilirsiniz.',
            'Endişeli olduğunuzda kendinizi kötü hissetmemeye çalışın ve destek arayın.',
            'Kendinize karşı nazik olun ve endişelerinizi yönetmek için rahatlama tekniklerini deneyin.',
            'Endişe genellikle geçici bir durumdur, bu yüzden kendinize nazik davranın.',
            'Derin nefes almak ve rahatlamaya çalışmak endişenizi azaltabilir.',
            'Küçük adımlar atarak endişelerinizi yönetebilir ve kendinizi daha iyi hissedebilirsiniz.',
            // 80 tane daha mesaj ekleyin
            'Kendinize nazik davranarak endişelerinizi yönetmeye çalışın.',
            'Endişeli olduğunuzda rahatlama tekniklerini deneyin ve kendinizi kötü hissetmemeye çalışın.',
            'Kendinize zaman ayırarak ve destek arayarak endişenizi azaltabilirsiniz.',
            'Endişe genellikle geçici bir durumdur, bu yüzden kendinize nazik davranın.',
            'Rahatlama tekniklerini deneyerek endişenizi azaltmaya çalışın.',
            'Endişeli olduğunuzda kendinizi kötü hissetmemeye çalışın ve destek arayın.',
            'Küçük adımlar atarak endişenizi yönetebilir ve kendinizi daha iyi hissedebilirsiniz.',
            'Endişe genellikle geçici bir durumdur. Kendinize nazik davranın ve rahatlama tekniklerini deneyin.',
            'Kendinize nazik davranarak endişelerinizi yönetmeye çalışın.',
            'Rahatlama tekniklerini kullanarak endişenizi azaltabilir ve kendinizi daha iyi hissedebilirsiniz.',
            'Kendinize zaman ayırarak ve destek arayarak endişenizi yönetmeye çalışın.',
            'Endişe genellikle geçici bir durumdur. Kendinize nazik davranın ve rahatlama tekniklerini deneyin.',
            'Küçük adımlar atarak endişenizi yönetebilir ve kendinizi daha iyi hissedebilirsiniz.',
            'Kendinize nazik davranarak endişelerinizi yönetmeye çalışın.',
            'Endişeli olduğunuzda rahatlama tekniklerini deneyin ve kendinizi kötü hissetmemeye çalışın.',
            'Kendinize zaman ayırarak ve destek arayarak endişenizi azaltabilirsiniz.',
            'Endişe genellikle geçici bir durumdur, bu yüzden kendinize nazik davranın.',
            'Rahatlama tekniklerini kullanarak endişenizi azaltabilir ve kendinizi daha iyi hissedebilirsiniz.',
            'Küçük adımlar atarak endişenizi yönetmeye çalışın ve destek arayın.'
        ],
        neutral: [
            'Bugün nötr bir ruh halindesiniz. Küçük şeylerle kendinizi mutlu edebilirsiniz. Küçük bir yürüyüş yapmayı deneyin.',
            'Nötr ruh hali genellikle denge ve huzur anlamına gelir. Bu dengeyi korumak için kendinize zaman ayırın.',
            'Günün tadını çıkarın ve keyif alabileceğiniz küçük aktiviteler planlayın.',
            'Nötr bir ruh hali, genellikle denge ve huzur anlamına gelir. Kendinizi iyi hissetmek için küçük şeyler yapabilirsiniz.',
            'Bugün kendinizi nötr hissettiğinizde, küçük şeyler kendinizi daha iyi hissettirebilir.',
            'Küçük şeylerle kendinizi mutlu etmeye çalışın. Bu, ruh halinizi iyileştirebilir.',
            'Nötr bir ruh hali, denge ve huzur anlamına gelir. Bu dengeyi korumak için kendinize zaman ayırın.',
            'Küçük şeyler kendinizi mutlu edebilir. Bu yüzden küçük aktiviteler planlayın.',
            'Nötr ruh halinizde kendinizi iyi hissetmek için küçük şeylerle kendinizi ödüllendirin.',
            'Günün tadını çıkarın ve kendinizi mutlu edecek küçük şeyler yapmayı deneyin.',
            'Nötr ruh hali genellikle denge ve huzur anlamına gelir. Bu dengeyi korumak için kendinize nazik davranın.',
            'Küçük aktiviteler kendinizi daha iyi hissettirebilir. Günün tadını çıkarın.',
            'Nötr ruh halinizde kendinizi mutlu etmek için küçük şeyler yapabilirsiniz.',
            'Günün tadını çıkarın ve kendinizi iyi hissetmek için küçük aktiviteler planlayın.',
            'Küçük şeylerle kendinizi mutlu etmeye çalışın ve günü keyifli hale getirin.',
            'Nötr bir ruh hali, denge ve huzur anlamına gelir. Bu dengeyi korumak için kendinize zaman ayırın.',
            'Küçük aktivitelerle kendinizi mutlu edin ve gününüzü güzelleştirin.',
            'Nötr ruh halinizde kendinizi iyi hissetmek için küçük şeyler yapabilirsiniz.',
            'Günün tadını çıkarın ve kendinizi mutlu edecek şeyler planlayın.',
            // 80 tane daha mesaj ekleyin
            'Nötr bir ruh hali, denge ve huzur anlamına gelir. Küçük şeylerle kendinizi mutlu edin.',
            'Küçük aktivitelerle kendinizi mutlu etmeye çalışın ve gününüzü güzelleştirin.',
            'Nötr bir ruh hali genellikle denge ve huzur anlamına gelir. Bu dengeyi korumak için kendinize nazik davranın.',
            'Günün tadını çıkarın ve kendinizi iyi hissetmek için küçük aktiviteler yapın.',
            'Nötr ruh halinizde kendinizi mutlu etmek için küçük şeylerle kendinizi ödüllendirin.',
            'Küçük şeylerle kendinizi mutlu edin ve günü keyifli hale getirin.',
            'Nötr ruh halinizde kendinizi iyi hissetmek için küçük şeyler yapabilirsiniz.',
            'Günün tadını çıkarın ve kendinizi mutlu edecek küçük aktiviteler planlayın.',
            'Nötr bir ruh hali, denge ve huzur anlamına gelir. Küçük şeylerle kendinizi mutlu edin.',
            'Küçük aktivitelerle kendinizi mutlu etmeye çalışın ve gününüzü güzelleştirin.',
            'Nötr bir ruh hali genellikle denge ve huzur anlamına gelir. Bu dengeyi korumak için kendinize nazik davranın.',
            'Günün tadını çıkarın ve kendinizi iyi hissetmek için küçük aktiviteler yapın.',
            'Nötr ruh halinizde kendinizi mutlu etmek için küçük şeylerle kendinizi ödüllendirin.',
            'Küçük şeylerle kendinizi mutlu edin ve günü keyifli hale getirin.',
            'Nötr ruh halinizde kendinizi iyi hissetmek için küçük şeyler yapabilirsiniz.',
            'Günün tadını çıkarın ve kendinizi mutlu edecek küçük aktiviteler planlayın.',
            'Nötr bir ruh hali, denge ve huzur anlamına gelir. Küçük şeylerle kendinizi mutlu edin.',
            'Küçük aktivitelerle kendinizi mutlu etmeye çalışın ve gününüzü güzelleştirin.'
        ]
    ,
    athlete: [
        'Her karanlık gecede bir ışık vardır, sadece onu bulmak gerekir. 🌟',
        'Güç, sadece düşmanın korkularını değil, kendi korkularını da aşmaktan gelir. 💪',
        'Küçük bir cesaret büyük değişimler yaratabilir. 🦸',
        'Zorluklar, bir kahramanın doğduğu yerlerdir. 🔥',
        'Sonsuz bir güce sahip olmasanız da, sonsuz bir cesarete sahip olabilirsiniz. 🌈',
        'Kahraman olmak, düşmemek değil, her düştüğünüzde tekrar kalkabilmektir. ⚔️',
        'Gerçek güç, zorluklar karşısında dimdik durmakta yatar. 🛡️',
        'Bir kahraman, en karanlık anlarda bile umudu ışık olarak taşır. 💫',
        'Savaşmaya devam et, çünkü umudun olmadığı yerlerde bile bir ışık vardır. 🕯️',
        'Küçük adımlar bile büyük bir kahramanın yolunu açabilir. 🚀',
        'Bir kahraman, yalnızca başkalarının değil, kendi hayatını da kurtarır. 🦸‍♂️',
        'Zorluklar, güç ve cesaretin gerçek testidir. ⚡',
        'Her mücadele, bir kahramanın doğuşunu simgeler. 🏅',
        'Bir kahramanın en büyük gücü, umudu asla kaybetmemesidir. 🌟',
        'Küçük eylemler büyük değişiklikler yaratır. 🌟',
        'Gerçek cesaret, korkunun üstesinden gelmektir. 🦹‍♀️',
        'Bir kahraman, en karanlık anlarda bile ışık olmaya devam eder. 🌠',
        'Kahramanlık, sadece büyük savaşlarda değil, küçük anlarda da gösterilir. 🎯',
        'Her zorluk, bir kahramanın gücünü ortaya çıkarır. 🔥',
        'Gerçek güç, sadece fiziksel değil, ruhsal bir güçtür. 🧠',
        'Bir kahramanın en büyük silahı, içindeki cesarettir. 🎖️',
        'Kahramanlar, zor zamanlarda bile umut taşır. 🕊️',
        'Cesaret, korkudan değil, inançtan doğar. 💫',
        'Her engel, bir kahramanın yolunu açar. 🚧',
        'Bir kahramanın gücü, en büyük zorluklardan bile çıkabilir. 💪',
        'Güçlü bir zihin, güçlü bir bedeni destekler. 🧠💪',
        'Savaşmaya devam et, çünkü her engel seni daha güçlü kılar. ⚔️',
        'Her adımda, içindeki kahramanı ortaya çıkar. 🦸‍♂️',
        'Başarı, cesaret ve azimle elde edilir. 🏆',
        'Bir kahramanın yolu, cesaretle kaplıdır. 🌟',
        'Zorluklar, gücünü kanıtlamak için fırsatlardır. 🔥',
        'İçindeki güç, seni her zaman ileriye taşıyacaktır. 💪',
        'Gerçek kahramanlar, umudu asla kaybetmezler. 🌟',
        'Küçük başarılar, büyük zaferlere dönüşür. 🏅',
        'Her zorluk, bir kahramanın gücünü test eder. ⚡',
        'Kahramanlar, her zaman içindeki gücü bulurlar. 💪',
        'Cesaret, en karanlık anlarda parlayan bir ışıktır. 💫',
        'Bir kahramanın gücü, mücadeleye olan bağlılığından gelir. 🦸‍♂️',
        'Küçük adımlar, büyük başarıların temelidir. 🌟',
        'Her engel, seni daha güçlü yapar. 💪',
        'Bir kahramanın en büyük gücü, içindeki cesarettir. 🎖️',
        'Güçlü olmak, sadece fiziksel değil, zihinsel bir savaş da gerektirir. 🧠💪',
        'Zorluklar, gerçek kahramanları ortaya çıkarır. 🔥',
        'Savaşmaya devam et, çünkü sen bir kahramansın. 🦸',
        'Başarı, kararlılıkla elde edilir. 🏆',
        'Güç, yalnızca fiziksel değil, ruhsal bir savaşın sonucudur. 🧠',
        'Her zorluk, seni daha da güçlendirir. 💪',
        'Kahramanlar, her zaman cesaretle doludur. 🌟',
        'Gerçek güç, her an ortaya çıkar. 💪',
        'Bir kahramanın yolu, cesaretle kaplıdır. 🦸‍♂️',
        'Küçük eylemler büyük zaferler getirir. 🏅',
        'Her başarısızlık, bir kahramanın başarısının bir parçasıdır. ⚡',
        'Güçlü kalın ve hedeflerinize odaklanın. 💪'
    ]
};


    const selectedMessages = messages[mood];
    const randomIndex = Math.floor(Math.random() * selectedMessages.length);
    result.textContent = selectedMessages[randomIndex];
});
